#!/bin/sh

if [[ $1 == upgrade ]]; then
	/bin/launchctl unload /Library/LaunchDaemons/com.test.imemXpcService.plist
fi

chown root:wheel /usr/bin/imemXpcService
chmod 755 /usr/bin/imemXpcService
chown root:wheel /Library/LaunchDaemons/com.test.imemXpcService.plist
chmod 644 /Library/LaunchDaemons/com.test.imemXpcService.plist

/bin/launchctl load /Library/LaunchDaemons/com.test.imemXpcService.plist

exit 0
